{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fact_crypto_price_data\",\"dim_crypto_id_and_name\",\"dim_calendar\",\"aux_measures\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "dimensions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "facts"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "auxiliaries"
      }
    ],
    "relationships": [
      {
        "name": "f97e3f3a-3db3-6f77-9a8f-072996b9bf45",
        "fromColumn": "ID",
        "fromTable": "fact_crypto_price_data",
        "toColumn": "ID",
        "toTable": "dim_crypto_id_and_name"
      },
      {
        "name": "5942e4d0-dab0-232e-fb4e-a3f99a745d6f",
        "fromColumn": "Date",
        "fromTable": "fact_crypto_price_data",
        "toColumn": "Date",
        "toTable": "dim_calendar"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "fact_crypto_price_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bc9c26cf-62c7-4c86-beb6-dfacb3514994",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d70bac22-e8e0-4e62-9a38-50ae361a6116",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Price (USD)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6748fdfe-7dcb-4cd3-85dd-c3f8cdc29f19",
            "sourceColumn": "Price (USD)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "17c6be94-d8c0-4653-be0c-f4bfc239a79a",
        "partitions": [
          {
            "name": "fact_crypto_price_data",
            "mode": "import",
            "queryGroup": "facts",
            "source": {
              "expression": [
                "let",
                "    // Source: CSV file from Google Drive",
                "    // The file is directly loaded using the public link from Google Drive in CSV format",
                "    Source = Csv.Document(",
                "        Web.Contents(\"https://drive.google.com/uc?id=1Zc8uFpZHPgJ_xgFp_bdBqJktLZd42DtQ&export=download\"), ",
                "        [Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]",
                "    ),",
                "    ",
                "    // Promote the first row as headers",
                "    // The first row of the CSV file will be used as column names",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "",
                "    // Change data types of the columns",
                "    // The 'ID' column is converted to Int64, 'Date' to datetime, and 'Price (USD)' to currency type",
                "    #\"Changed Type\" = Table.TransformColumnTypes(",
                "        #\"Promoted Headers\", ",
                "        {{\"ID\", Int64.Type}, {\"Date\", type datetime}, {\"Price (USD)\", Currency.Type}}",
                "    ),",
                "",
                "    // Filter rows where the time in the 'Date' column is exactly 12:00:00AM",
                "    // Only rows where the time is midnight are kept",
                "    #\"Filtered Rows\" = Table.SelectRows(",
                "        #\"Changed Type\", ",
                "        each DateTime.ToText([Date], \"HH:mm:ss\") = \"00:00:00\"",
                "    ),",
                "",
                "    // Change the 'Date' column type to date only (removing the time part)",
                "    // This removes the time, keeping only the date value",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows\", {{\"Date\", type date}})",
                "in",
                "    // Returns the final table with all transformations applied",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_crypto_id_and_name",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDefaultLabel": true,
            "lineageTag": "d27dacdd-bcf6-4dc9-9ebe-af5ad853a85d",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Coin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23018f32-baa7-4a1d-8843-b0b1bc45818f",
            "sourceColumn": "Coin",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a81679a2-b180-48ab-9907-5aa236677d0f",
        "partitions": [
          {
            "name": "dim_crypto_id_and_name",
            "mode": "import",
            "queryGroup": "dimensions",
            "source": {
              "expression": [
                "let",
                "    // Source: CSV file from Google Drive",
                "    // The file is directly loaded using the public link from Google Drive in CSV format",
                "    Source = Csv.Document(",
                "        Web.Contents(\"https://drive.google.com/uc?id=1G7iAckxC7_xWpp0_Nv-nKSCBkzjTIwX3&export=download\"), ",
                "        [Delimiter=\",\", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]",
                "    ),",
                "    ",
                "    // Promote the first row as headers",
                "    // The first row of the CSV file will be used as column names",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "",
                "    // Change data types of the columns",
                "    // The 'ID' column is converted to Int64 and the 'Coin' column to text",
                "    #\"Changed Type\" = Table.TransformColumnTypes(",
                "        #\"Promoted Headers\", ",
                "        {{\"ID\", Int64.Type}, {\"Coin\", type text}}",
                "    )",
                "in",
                "    // Returns the final table with all transformations applied",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isDefaultLabel": true,
            "isKey": true,
            "lineageTag": "a1365db1-a6af-4b1d-8e0d-86210af55ace",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b3f5897-ad20-4443-b8b9-21a1cce218a0",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73589f35-1a5e-4a3a-85ef-e470e14187b1",
            "sourceColumn": "Week",
            "summarizeBy": "none"
          },
          {
            "name": "Week Abbrev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d00d541-6fa9-4a5e-b222-9e18bc2078d5",
            "sourceColumn": "Week Abbrev",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc2dfad7-72c2-4075-906f-759d9f5b9ac1",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48e7fbb7-d47d-4ad6-b2a6-0b393fe29e91",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73bd66ee-06c1-41e7-b38d-89812fee72e3",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonthSeq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c95957b-9ec2-434e-8be3-c9af78464666",
            "sourceColumn": "YearMonthSeq",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb42120a-89b4-40a6-a3cf-4fac913d6b1c",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "9ec220d0-c966-484d-b021-5429419dee80",
        "partitions": [
          {
            "name": "dim_calendar",
            "mode": "import",
            "queryGroup": "dimensions",
            "source": {
              "expression": [
                "let",
                "    // Start Date",
                "    StartDate = #date(2025,1,1),",
                "    // End date of the calendar:",
                "    // Last date of the next year --> Date.AddYears(Date.EndOfYear(Date.From(DateTime.LocalNow())),1),",
                "    // Last date of the current year --> Date.EndOfYear(Date.From(DateTime.LocalNow())),",
                "    // Last date of the current month --> Date.EndOfMonth(Date.From(DateTime.LocalNow())),",
                "    // Today --> Date.From(DateTime.LocalNow()),",
                "    EndDate = Date.EndOfYear(Date.From(DateTime.LocalNow())), // Last date of the current year",
                "    // Number of days between StartDate and EndDate",
                "    NumberOfDays = Duration.TotalDays(EndDate-StartDate)+1,",
                "    // List of Dates",
                "    Source = List.Dates(StartDate,NumberOfDays,#duration(1,0,0,0)),",
                "    // Calendar Table",
                "    CalendarTable = #table(",
                "        type table[",
                "            Date=date, ",
                "            Day=Int64.Type,  ",
                "            Week = text, ",
                "            Week Abbrev = text, ",
                "            Month Name= text, ",
                "            Quarter = text,  ",
                "            Year = Int64.Type,  ",
                "            YearMonthSeq = Int64.Type, ",
                "            MonthYear = text",
                "        ],",
                "        List.Transform(",
                "            Source, ",
                "            each {",
                "                _, // Date 01/01/2025, 02/01/2025, ...",
                "                Date.Day(_), // Day 1, 2, 3...",
                "                Text.Repeat(Character.FromNumber(8203), 7 - Date.DayOfWeek(_)) & Text.BeforeDelimiter(Text.Proper(Date.ToText(_,\"dddd\", \"en-US\")),\"-\"), // Full Weekday Name Monday, Tuesday, Wednesday, ...",
                "                Text.Repeat(Character.FromNumber(8203), 7 - Date.DayOfWeek(_)) & Text.Proper(Date.ToText(_,\"ddd\", \"en-US\")), // Abbreviated Weekday Name Mon, Tue, Wed, ...",
                "                Text.Repeat(Character.FromNumber(8203), 12 - Date.Month(_)) & Text.Proper(Date.ToText(_,\"MMM\", \"en-US\")), // Month Name Jan, Feb, Mar,",
                "                \"Q\" & Text.From(Date.QuarterOfYear(_)), // Quarter Q1, Q2, Q3, Q4",
                "                Date.Year(_), // Year 2021, 2022, ...",
                "                12 * Date.Year(_) + Date.Month(_) - 1, // Sequential Year/Month Number 24287, 24286, ...",
                "                Text.Proper(Date.ToText(_,\"MMM/yyyy\")) // Month Year Jan/2022, Feb/2022, ...",
                "            }",
                "        )",
                "    )",
                "in",
                "    CalendarTable"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "aux_measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "d650f732-a3b8-458d-b74d-d311cb078245",
        "measures": [
          {
            "name": "Max Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "MAX(fact_crypto_price_data[Price (USD)])"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3a77e333-8eb3-4d1d-ae27-5565612c0a89"
          },
          {
            "name": "Average Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "AVERAGE(fact_crypto_price_data[Price (USD)])",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1bb53d0d-9907-4168-a4e6-f0897600d160"
          },
          {
            "name": "Min Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "MIN(fact_crypto_price_data[Price (USD)])"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "48770a8a-54b0-47f7-86ee-3e025171fee8"
          }
        ],
        "partitions": [
          {
            "name": "aux_measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Coluna 1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Coluna 1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}