{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fact_crypto_price_data\",\"dim_crypto_id_and_name\",\"dim_calendar\",\"aux_measures\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "dimensions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "facts"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "auxiliaries"
      }
    ],
    "relationships": [
      {
        "name": "bc0b2913-44ea-2998-9e17-4bb9e5cced5c",
        "fromColumn": "Date",
        "fromTable": "fact_crypto_price_data",
        "toColumn": "Date",
        "toTable": "dim_calendar"
      },
      {
        "name": "691fe365-708f-3f66-8adf-12228d246f51",
        "fromColumn": "ID",
        "fromTable": "fact_crypto_price_data",
        "toColumn": "ID",
        "toTable": "dim_crypto_id_and_name"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "fact_crypto_price_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Close",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ad5e9ee1-bcce-4046-bbc8-fe23d44c6d64",
            "sourceColumn": "Close",
            "summarizeBy": "sum"
          },
          {
            "name": "High",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "104b0efa-8a31-4fb8-8291-ba9453ad9957",
            "sourceColumn": "High",
            "summarizeBy": "sum"
          },
          {
            "name": "Low",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "7812d6dd-62f8-4cde-98ce-216006d6ae80",
            "sourceColumn": "Low",
            "summarizeBy": "sum"
          },
          {
            "name": "Open",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ee408d1e-86e0-4e9d-9925-e61db639b810",
            "sourceColumn": "Open",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41b27dae-e5fe-4ff0-88d2-d0e27e0097a4",
            "sourceColumn": "Volume",
            "summarizeBy": "sum"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ece9a53-a472-463f-acf7-b2812c437c78",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4a13b22d-09ad-4235-a217-dec17e716230",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "17c6be94-d8c0-4653-be0c-f4bfc239a79a",
        "partitions": [
          {
            "name": "fact_crypto_price_data",
            "mode": "import",
            "queryGroup": "facts",
            "source": {
              "expression": [
                "let",
                "    // Source: CSV file from Google Drive",
                "    // The file is directly loaded using the public link from Google Drive in CSV format",
                "    Source = Csv.Document(",
                "        Web.Contents(\"https://drive.google.com/uc?id=1Zc8uFpZHPgJ_xgFp_bdBqJktLZd42DtQ&export=download\"), ",
                "        [Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]",
                "    ),",
                "    ",
                "    // Promote the first row as headers",
                "    // The first row of the CSV file is treated as column headers instead of data",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "",
                "    // Remove the top 2 rows",
                "    // Skips the first 2 rows of the table, assuming they contain unwanted data or metadata",
                "    #\"Removed Top Rows\" = Table.Skip(#\"Promoted Headers\", 2),",
                "",
                "    // Change column data types",
                "    // Ensures proper data types for each column:",
                "    // - \"Date\" column is converted to a date type",
                "    // - \"Close\", \"High\", \"Low\", and \"Open\" columns are set to currency type for consistency in financial data",
                "    // - \"Volume\" column is set to a 64-bit integer type to handle large values",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Top Rows\", {",
                "        {\"ID\", Int64.Type},",
                "        {\"Date\", type date}, ",
                "        {\"Close\", Currency.Type}, ",
                "        {\"High\", Currency.Type}, ",
                "        {\"Low\", Currency.Type}, ",
                "        {\"Open\", Currency.Type}, ",
                "        {\"Volume\", Int64.Type}",
                "    })",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_crypto_id_and_name",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDefaultLabel": true,
            "lineageTag": "d27dacdd-bcf6-4dc9-9ebe-af5ad853a85d",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Crypto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "baa49fd6-44d9-4fb1-a55a-4e809ade4870",
            "sourceColumn": "Crypto",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f3d0ced-2cf3-42dc-ad4b-c4105e15b9a9",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a81679a2-b180-48ab-9907-5aa236677d0f",
        "partitions": [
          {
            "name": "dim_crypto_id_and_name",
            "mode": "import",
            "queryGroup": "dimensions",
            "source": {
              "expression": [
                "let",
                "    // Source: CSV file from Google Drive",
                "    // The file is directly loaded using the public link from Google Drive in CSV format",
                "    Source = Csv.Document(",
                "        Web.Contents(\"https://drive.google.com/uc?id=1G7iAckxC7_xWpp0_Nv-nKSCBkzjTIwX3&export=download\"), ",
                "        [Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]",
                "    ),",
                "    ",
                "    // Promote the first row as headers",
                "    // The first row of the CSV file will be used as column names",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "",
                "    // Change data types of the columns",
                "    // The 'ID' column is converted to Int64 and the 'Coin' column to text",
                "    #\"Changed Type\" = Table.TransformColumnTypes(",
                "        #\"Promoted Headers\", ",
                "        {{\"ID\", Int64.Type}, {\"Crypto\", type text}, {\"Name\", type text}}",
                "    )",
                "in",
                "    // Returns the final table with all transformations applied",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isDefaultLabel": true,
            "isKey": true,
            "lineageTag": "a1365db1-a6af-4b1d-8e0d-86210af55ace",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b3f5897-ad20-4443-b8b9-21a1cce218a0",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73589f35-1a5e-4a3a-85ef-e470e14187b1",
            "sourceColumn": "Week",
            "summarizeBy": "none"
          },
          {
            "name": "Week Abbrev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d00d541-6fa9-4a5e-b222-9e18bc2078d5",
            "sourceColumn": "Week Abbrev",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc2dfad7-72c2-4075-906f-759d9f5b9ac1",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48e7fbb7-d47d-4ad6-b2a6-0b393fe29e91",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73bd66ee-06c1-41e7-b38d-89812fee72e3",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonthSeq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c95957b-9ec2-434e-8be3-c9af78464666",
            "sourceColumn": "YearMonthSeq",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb42120a-89b4-40a6-a3cf-4fac913d6b1c",
            "sortByColumn": "YearMonthSeq",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "776fd290-097f-481c-b91b-ee74c88231e3",
                "ordinal": 0
              },
              {
                "name": "MonthYear",
                "column": "MonthYear",
                "lineageTag": "1e491b7a-8490-4443-b8a4-5550ff5315a3",
                "ordinal": 1
              },
              {
                "name": "Date",
                "column": "Date",
                "lineageTag": "babe7bb7-6760-4321-9e6e-242735b5b775",
                "ordinal": 2
              }
            ],
            "lineageTag": "0376b92c-c44d-4e67-a593-ea1f359b2714"
          }
        ],
        "lineageTag": "9ec220d0-c966-484d-b021-5429419dee80",
        "partitions": [
          {
            "name": "dim_calendar",
            "mode": "import",
            "queryGroup": "dimensions",
            "source": {
              "expression": [
                "let",
                "    // Start Date",
                "    StartDate = #date(2014,1,1),",
                "    // End date of the calendar:",
                "    // Last date of the next year --> Date.AddYears(Date.EndOfYear(Date.From(DateTime.LocalNow())),1),",
                "    // Last date of the current year --> Date.EndOfYear(Date.From(DateTime.LocalNow())),",
                "    // Last date of the current month --> Date.EndOfMonth(Date.From(DateTime.LocalNow())),",
                "    // Today --> Date.From(DateTime.LocalNow()),",
                "    EndDate = Date.EndOfYear(Date.From(DateTime.LocalNow())), // Last date of the current year",
                "    // Number of days between StartDate and EndDate",
                "    NumberOfDays = Duration.TotalDays(EndDate-StartDate)+1,",
                "    // List of Dates",
                "    Source = List.Dates(StartDate,NumberOfDays,#duration(1,0,0,0)),",
                "    // Calendar Table",
                "    CalendarTable = #table(",
                "        type table[",
                "            Date=date, ",
                "            Day=Int64.Type,  ",
                "            Week = text, ",
                "            Week Abbrev = text, ",
                "            Month Name= text, ",
                "            Quarter = text,  ",
                "            Year = Int64.Type,  ",
                "            YearMonthSeq = Int64.Type, ",
                "            MonthYear = text",
                "        ],",
                "        List.Transform(",
                "            Source, ",
                "            each {",
                "                _, // Date 01/01/2025, 02/01/2025, ...",
                "                Date.Day(_), // Day 1, 2, 3...",
                "                Text.Repeat(Character.FromNumber(8203), 7 - Date.DayOfWeek(_)) & Text.BeforeDelimiter(Text.Proper(Date.ToText(_,\"dddd\", \"en-US\")),\"-\"), // Full Weekday Name Monday, Tuesday, Wednesday, ...",
                "                Text.Repeat(Character.FromNumber(8203), 7 - Date.DayOfWeek(_)) & Text.Proper(Date.ToText(_,\"ddd\", \"en-US\")), // Abbreviated Weekday Name Mon, Tue, Wed, ...",
                "                Text.Repeat(Character.FromNumber(8203), 12 - Date.Month(_)) & Text.Proper(Date.ToText(_,\"MMM\", \"en-US\")), // Month Name Jan, Feb, Mar,",
                "                \"Q\" & Text.From(Date.QuarterOfYear(_)), // Quarter Q1, Q2, Q3, Q4",
                "                Date.Year(_), // Year 2021, 2022, ...",
                "                12 * Date.Year(_) + Date.Month(_) - 1, // Sequential Year/Month Number 24287, 24286, ...",
                "                Text.Proper(Date.ToText(_,\"MMM/yyyy\")) // Month Year Jan/2022, Feb/2022, ...",
                "            }",
                "        )",
                "    )",
                "in",
                "    CalendarTable"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "aux_measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "d650f732-a3b8-458d-b74d-d311cb078245",
        "measures": [
          {
            "name": "High Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "MAX(fact_crypto_price_data[High])"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3a77e333-8eb3-4d1d-ae27-5565612c0a89"
          },
          {
            "name": "Average Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "DIVIDE([Open Price]+[Close Price],2)",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "1bb53d0d-9907-4168-a4e6-f0897600d160"
          },
          {
            "name": "Low Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "MIN(fact_crypto_price_data[Low])"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "48770a8a-54b0-47f7-86ee-3e025171fee8"
          },
          {
            "name": "Close Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fact_crypto_price_data[Close]),",
              "    fact_crypto_price_data[Date] = MAX(fact_crypto_price_data[Date])",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "f4326902-6caa-4ebf-bd8b-02e9a354a21c"
          },
          {
            "name": "Open Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(fact_crypto_price_data[Open]),",
              "    fact_crypto_price_data[Date] = MIN(fact_crypto_price_data[Date])",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "47ed6069-2a0a-4667-9aab-7d78b75a6064"
          },
          {
            "name": "Volume",
            "expression": "SUM(fact_crypto_price_data[Volume])",
            "formatString": "#,0",
            "lineageTag": "c691f322-9e5d-4cbf-8619-a093003bda4a"
          },
          {
            "name": "Percentage Change",
            "expression": [
              "",
              "DIVIDE(",
              "    ([Close Price] - [Open Price]), ",
              "    [Open Price]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a4ab4b45-891c-434f-a7c8-0c3fc592c243"
          }
        ],
        "partitions": [
          {
            "name": "aux_measures",
            "mode": "import",
            "queryGroup": "auxiliaries",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Coluna 1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Coluna 1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}